### ISSUE TITLE
README Change

### ISSUE THREAD

**Issue by elliotcondon** [mikerodriguez/acf-paypal-field#1]
Hey @mikerodriguez 

Great work on the plugin. I've spotted an issue in the readme which I have since updated the field type template files.

The installation instructions currently say:

```
add_action('acf/register_fields', 'my_register_fields');

function my_register_fields()
{
    include_once('acf-paypal-field/acf-paypal.php');
}
```

However, they should say:

```
include_once('acf-paypal-field/acf-paypal.php');
```

Cheers
Elliot

**Comment by mikerodriguez** [comment]
Thanks Elliot! 

just changed it.
